name: medicinestore
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter  



  cupertino_icons: ^1.0.6

  #Network and Api
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  dio_cache_interceptor: ^3.5.0
  connectivity_plus: ^6.0.3
 
  #Responcive UI
  sizer: ^2.0.15

  #State Mangement
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4 

  #storage
  shared_preferences: ^2.2.3
  



  # UI 
  shimmer: ^3.0.0
  page_transition: "^2.1.0"
  dropdown_button2: ^2.3.9
  numberpicker: ^2.1.2
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  pull_to_refresh: ^2.0.0
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.1
  smooth_page_indicator: ^1.1.0
  image_picker: ^1.1.1
  loading_indicator: ^3.1.1
  country_picker: ^2.0.26
  flutter_verification_code: ^1.1.7
  url_launcher: ^6.2.6



  # #Location
  # meta: ^1.12.0
  # geolocator: ^12.0.0
  # geocoding: ^3.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0




flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/en.json
    - assets/translations/ar.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
